"use client"

import type React from "react"

import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Slider } from "@/components/ui/slider"
import { useState, useEffect, useRef, useCallback } from "react"
import { ChevronDown, Play, RotateCcw, Timer, Pause, Upload } from "lucide-react"
import * as XLSX from "xlsx"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"

type WordPair = [string, string]
type GameCard = {
  id: string
  text: string
  pairId: number
  status: "visible" | "selected" | "mismatched" | "matched"
  color: string
}
type GameState = "idle" | "playing" | "finished"
type WordLists = { [key: string]: WordPair[] }

// --- Embedded Default Word Lists ---
const defaultWordsA: WordPair[] = [
  ["happy", "开心"],
  ["mad", "生气"],
  ["sad", "伤心"],
  ["shy", "害羞"],
  ["sleepy", "困"],
  ["scared", "害怕"],
  ["kid", "小孩"],
  ["cub", "幼崽"],
  ["calf", "小牛"],
  ["chick", "小鸡"],
  ["lamb", "小羊"],
  ["foal", "小马"],
  ["many", "很多"],
  ["count", "数"],
  ["two", "二"],
  ["five", "五"],
  ["four", "四"],
  ["three", "三"],
  ["one", "一"],
  ["I", "我"],
  ["six", "六"],
  ["seven", "七"],
  ["sheep", "羊"],
  ["color", "颜色"],
  ["bird", "鸟"],
  ["blue", "蓝色"],
  ["brown", "棕色"],
  ["gray", "灰色"],
  ["green", "绿色"],
  ["orange", "橙色"],
  ["pink", "粉色"],
  ["purple", "紫色"],
  ["red", "红色"],
  ["yellow", "黄色"],
  ["city", "城市"],
  ["car", "车"],
  ["tree", "树"],
  ["street", "街道"],
  ["farm", "农场"],
  ["crayon", "蜡笔"],
  ["eraser", "橡皮"],
  ["ruler", "尺子"],
  ["pencil", "铅笔"],
  ["sweater", "毛衣"],
  ["backpack", "背包"],
  ["door", "门"],
  ["window", "窗"],
  ["engine", "引擎"],
  ["wheel", "车轮"],
  ["seat", "座位"],
  ["light", "灯"],
  ["trunk", "后备箱"],
  ["fruit", "水果"],
  ["apple", "苹果"],
  ["banana", "香蕉"],
  ["lemon", "柠檬"],
  ["cherry", "樱桃"],
  ["pear", "梨"],
  ["float", "漂浮"],
  ["dive", "潜水"],
  ["swim", "游泳"],
  ["play", "玩耍"],
  ["sail", "航行"],
  ["water", "水"],
  ["fish", "鱼"],
  ["paddle", "划桨"],
  ["splash", "飞溅"],
  ["hat", "帽子"],
  ["jacket", "夹克"],
  ["pants", "裤子"],
  ["shirt", "衬衫"],
  ["socks", "袜子"],
  ["glasses", "眼镜"],
  ["train", "火车"],
  ["horse", "马"],
  ["bike", "自行车"],
  ["plane", "飞机"],
  ["skateboard", "滑板"],
  ["food", "食物"],
  ["nest", "巢"],
  ["home", "家"],
  ["hamster", "仓鼠"],
  ["cage", "笼子"],
  ["tube", "管子"],
  ["pool", "游泳池"],
  ["place", "地方"],
  ["hot", "热"],
  ["cold", "冷"],
  ["thing", "东西"],
  ["people", "人"],
  ["out", "外面"],
  ["in", "里面"],
  ["jump", "跳跃"],
  ["run", "跑"],
  ["crawl", "爬"],
  ["hop", "跳"],
  ["climb", "攀爬"],
  ["ride", "骑"],
  ["swing", "秋千"],
  ["teeth", "牙齿"],
  ["ears", "耳朵"],
  ["draw", "画"],
  ["bunny", "兔子"],
  ["tail", "尾巴"],
  ["body", "身体"],
  ["flower", "花"],
  ["love", "爱"],
  ["daisy", "雏菊"],
  ["lily", "百合"],
  ["mum", "菊花"],
  ["save", "存"],
  ["quarter", "25美分"],
  ["nickel", "5美分"],
  ["dime", "10美分"],
  ["penny", "1美分"],
  ["dollar", "美元"],
  ["gold", "金色"],
  ["knife", "刀"],
  ["plate", "盘子"],
  ["fork", "叉子"],
  ["spoon", "勺子"],
  ["glass", "玻璃杯"],
  ["cloth", "布"],
  ["napkin", "餐巾"],
  ["pumpkin", "南瓜"],
  ["lunch", "午餐"],
  ["brother", "兄弟"],
  ["elephant", "大象"],
  ["zebra", "斑马"],
  ["ape", "猿"],
  ["dolphin", "海豚"],
  ["kangaroo", "袋鼠"],
  ["giraffe", "长颈鹿"],
  ["head", "头"],
  ["chest", "胸部"],
  ["leg", "腿"],
  ["arm", "手臂"],
  ["belly", "肚子"],
  ["sit", "坐"],
  ["dig", "挖"],
  ["roll", "滚"],
  ["hug", "拥抱"],
  ["cheek", "脸颊"],
  ["mouth", "嘴"],
  ["nose", "鼻子"],
  ["chin", "下巴"],
  ["eyes", "眼睛"],
  ["eyebrow", "眉毛"],
  ["hair", "头发"],
  ["long", "长"],
  ["short", "短"],
  ["black", "黑色"],
  ["straight", "直的"],
  ["blond", "金发"],
  ["bathroom", "浴室"],
  ["bedroom", "卧室"],
  ["house", "房子"],
  ["kitchen", "厨房"],
  ["living room", "客厅"],
  ["dining room", "餐厅"],
  ["hall", "走廊"],
  ["room", "房间"],
  ["bed", "床"],
  ["desk", "书桌"],
  ["clothes", "衣服"],
  ["toy", "玩具"],
  ["shoes", "鞋"],
  ["up", "上"],
  ["down", "下"],
  ["open", "打开"],
  ["closed", "关闭"],
  ["on", "打开"],
  ["off", "关闭"],
  ["pond", "池塘"],
  ["duck", "鸭子"],
  ["turtle", "乌龟"],
  ["frog", "青蛙"],
  ["swan", "天鹅"],
  ["fluffy", "蓬松"],
  ["rabbit", "兔子"],
  ["big", "大"],
  ["small", "小"],
  ["tall", "高"],
  ["fast", "快"],
  ["white", "白色"],
  ["triangle", "三角形"],
  ["circle", "圆形"],
  ["square", "正方形"],
  ["oval", "椭圆形"],
  ["shape", "形状"],
  ["star", "星星"],
  ["heart", "心形"],
  ["spiral", "螺旋"],
  ["sun", "太阳"],
  ["cloud", "云"],
  ["rain", "雨"],
  ["storm", "风暴"],
  ["fog", "雾"],
  ["wet", "湿"],
  ["old", "旧"],
  ["funny", "有趣"],
  ["shiny", "闪亮"],
  ["look", "看"],
  ["clean", "清洁"],
  ["hide", "躲藏"],
  ["sleep", "睡觉"],
  ["stream", "溪流"],
  ["forest", "森林"],
  ["fox", "狐狸"],
  ["deer", "鹿"],
  ["squirrel", "松鼠"],
  ["mushroom", "蘑菇"],
  ["flag", "旗帜"],
  ["balloon", "气球"],
  ["drum", "鼓"],
  ["parade", "游行"],
  ["clown", "小丑"],
  ["rainbow", "彩虹"],
  ["sky", "天空"],
  ["puddle", "水坑"],
  ["lightning", "闪电"],
  ["feet", "脚"],
  ["soft", "柔软"],
  ["fur", "毛皮"],
  ["fat", "胖"],
  ["hand", "手"],
  ["tap", "轻拍"],
  ["clap", "拍手"],
  ["stomp", "跺脚"],
  ["snap", "打响指"],
  ["pop", "弹"],
  ["slap", "拍打"],
  ["outside", "外面"],
  ["slide", "滑梯"],
  ["child", "孩子"],
  ["bee", "蜜蜂"],
  ["worm", "蠕虫"],
  ["dance", "跳舞"],
  ["leap", "跳跃"],
  ["bend", "弯曲"],
  ["spin", "旋转"],
  ["prance", "欢跳"],
  ["skip", "跳跃"],
  ["step", "步伐"],
]
const defaultWordsAA: WordPair[] = [
  ["animal", "动物"],
  ["dog", "狗"],
  ["duck", "鸭子"],
  ["pig", "猪"],
  ["cow", "牛"],
  ["chicken", "鸡"],
  ["sheep", "羊"],
  ["goat", "山羊"],
  ["many", "很多"],
  ["bug", "虫子"],
  ["one", "一"],
  ["two", "二"],
  ["three", "三"],
  ["four", "四"],
  ["five", "五"],
  ["six", "六"],
  ["seven", "七"],
  ["door", "门"],
  ["window", "窗户"],
  ["bus", "公交车"],
  ["school", "学校"],
  ["seat", "座位"],
  ["bench", "长椅"],
  ["walk", "走路"],
  ["the", "这个"],
  ["step", "台阶"],
  ["bear", "熊"],
  ["lion", "狮子"],
  ["elephant", "大象"],
  ["tiger", "老虎"],
  ["frog", "青蛙"],
  ["monkey", "猴子"],
  ["panda", "熊猫"],
  ["bird", "鸟"],
  ["cat", "猫"],
  ["bunny", "兔子"],
  ["turtle", "乌龟"],
  ["mouse", "老鼠"],
  ["goldfish", "金鱼"],
  ["hamster", "仓鼠"],
  ["gift", "礼物"],
  ["hug", "拥抱"],
  ["smile", "微笑"],
  ["card", "卡片"],
  ["kiss", "吻"],
  ["lick", "舔"],
  ["pat", "拍"],
  ["wink", "眨眼"],
  ["house", "房子"],
  ["car", "汽车"],
  ["tree", "树"],
  ["big", "大"],
  ["dinosaur", "恐龙"],
  ["plane", "飞机"],
  ["kitten", "小猫"],
  ["has", "有"],
  ["Colorful", "五颜六色"],
  ["egg", "蛋"],
  ["a", "一个"],
  ["an", "一个"],
  ["blue", "蓝色"],
  ["green", "绿色"],
  ["orange", "橙色"],
  ["pink", "粉色"],
  ["purple", "紫色"],
  ["red", "红色"],
  ["yellow", "黄色"],
  ["boots", "靴子"],
  ["hat", "帽子"],
  ["sweater", "毛衣"],
  ["sunglasses", "太阳镜"],
  ["mask", "面具"],
  ["cape", "披风"],
  ["boat", "船"],
  ["airplane", "飞机"],
  ["truck", "卡车"],
  ["wagon", "马车"],
  ["cart", "手推车"],
  ["moon", "月亮"],
  ["leaf", "叶子"],
  ["apple", "苹果"],
  ["rake", "耙子"],
  ["jacket", "夹克"],
  ["pumpkin", "南瓜"],
  ["acorn", "橡子"],
  ["corn", "玉米"],
  ["jump", "跳跃"],
  ["girl", "女孩"],
  ["over", "结束"],
  ["little", "小"],
  ["baby", "婴儿"],
  ["lunch", "午餐"],
  ["milk", "牛奶"],
  ["friend", "朋友"],
  ["my", "我的"],
  ["carrot", "胡萝卜"],
  ["bag", "包"],
  ["brother", "兄弟"],
  ["family", "家庭"],
  ["father", "父亲"],
  ["mother", "母亲"],
  ["sister", "姐妹"],
  ["paper", "纸"],
  ["box", "盒子"],
  ["bowl", "碗"],
  ["day", "天"],
  ["bow", "弓"],
  ["fence", "围栏"],
  ["bed", "床"],
  ["table", "桌子"],
  ["skates", "溜冰鞋"],
  ["swing", "秋千"],
  ["bike", "自行车"],
  ["body", "身体"],
  ["head", "头"],
  ["legs", "腿"],
  ["hole", "洞"],
  ["log", "原木"],
  ["pot", "锅"],
  ["bat", "蝙蝠"],
  ["pasta", "意大利面"],
  ["long", "长"],
  ["short", "短"],
  ["wide", "宽"],
  ["thin", "薄"],
  ["curly", "卷曲"],
  ["yummy", "美味"],
  ["baseball", "棒球"],
  ["basketball", "篮球"],
  ["football", "足球"],
  ["golf", "高尔夫球"],
  ["tennis", "网球"],
  ["volleyball", "排球"],
  ["rain", "雨"],
  ["spring", "春天"],
  ["flower", "花"],
  ["rainbow", "彩虹"],
  ["ball", "球"],
  ["summer", "夏天"],
  ["fun", "乐趣"],
  ["plate", "盘子"],
  ["picnic", "野餐"],
  ["cup", "杯子"],
  ["garden", "花园"],
  ["beach", "海滩"],
  ["swimsuit", "泳衣"],
  ["sunshine", "阳光"],
  ["backyard", "后院"],
  ["hose", "水管"],
  ["book", "书"],
  ["number", "数字"],
  ["title", "标题"],
  ["letter", "字母"],
  ["word", "单词"],
  ["page", "页面"],
  ["park", "公园"],
  ["street", "街道"],
  ["store", "商店"],
  ["building", "建筑物"],
  ["classroom", "教室"],
  ["desk", "书桌"],
  ["pencil", "铅笔"],
  ["coast", "海岸"],
  ["ocean", "海洋"],
  ["lighthouse", "灯塔"],
  ["rock", "岩石"],
  ["wave", "波浪"],
  ["cliff", "悬崖"],
  ["game", "游戏"],
  ["pillow", "枕头"],
  ["blanket", "毯子"],
  ["light", "灯"],
  ["beans", "豆子"],
  ["onion", "洋葱"],
  ["melon", "甜瓜"],
  ["peas", "豌豆"],
  ["potato", "土豆"],
  ["tomato", "番茄"],
  ["fish", "鱼"],
  ["sand", "沙子"],
  ["crab", "螃蟹"],
  ["starfish", "海星"],
  ["coral", "珊瑚"],
  ["seaweed", "海藻"],
  ["seed", "种子"],
  ["plant", "植物"],
  ["shovel", "铲子"],
  ["dirt", "泥土"],
  ["gym", "健身房"],
  ["library", "图书馆"],
  ["lunchroom", "餐厅"],
  ["playground", "操场"],
  ["gate", "大门"],
  ["bread", "面包"],
  ["fruit", "水果"],
  ["meat", "肉"],
  ["vegetable", "蔬菜"],
  ["cart", "购物车"],
  ["checkout", "结账"],
  ["map", "地图"],
  ["grandparent", "祖父母"],
  ["clothes", "衣服"],
  ["suitcase", "行李箱"],
  ["cookie", "饼干"],
  ["belly", "肚子"],
  ["pie", "派"],
  ["cupcake", "纸杯蛋糕"],
  ["brownie", "布朗尼"],
  ["paint", "油漆"],
  ["kite", "风筝"],
  ["drum", "鼓"],
  ["robot", "机器人"],
  ["under", "在下面"],
  ["umbrella", "伞"],
  ["lake", "湖"],
  ["river", "河流"],
  ["snow", "雪"],
  ["ice", "冰"],
  ["build", "建造"],
  ["drill", "钻"],
  ["saw", "锯"],
  ["hammer", "锤子"],
  ["hang", "挂"],
  ["winter", "冬天"],
  ["mittens", "手套"],
  ["coat", "外套"],
  ["sled", "雪橇"],
]
const defaultWordsB: WordPair[] = [
  ["swim", "游泳"],
  ["walk", "走路"],
  ["hop", "跳跃"],
  ["fly", "飞"],
  ["move", "移动"],
  ["hair", "头发"],
  ["shell", "贝壳"],
  ["feather", "羽毛"],
  ["scales", "鳞片"],
  ["fur", "毛皮"],
  ["skin", "皮肤"],
  ["spines", "刺"],
  ["have", "有"],
  ["we", "我们"],
  ["armor", "盔甲"],
  ["just", "只是"],
  ["round", "圆的"],
  ["long", "长的"],
  ["big", "大的"],
  ["small", "小的"],
  ["does", "做"],
  ["this", "这个"],
  ["striped", "有条纹的"],
  ["pointed", "尖的"],
  ["ear", "耳朵"],
  ["spotted", "有斑点的"],
  ["bark", "狗叫"],
  ["meow", "猫叫"],
  ["moo", "牛叫"],
  ["oink", "猪叫"],
  ["quack", "鸭叫"],
  ["hiss", "嘶嘶声"],
  ["buzz", "嗡嗡声"],
  ["roar", "咆哮"],
  ["chirp", "鸟叫"],
  ["snore", "打鼾"],
  ["apple", "苹果"],
  ["cut", "切"],
  ["cook", "烹饪"],
  ["add", "添加"],
  ["cinnamon", "肉桂"],
  ["mash", "捣碎"],
  ["green", "绿色"],
  ["red", "红色"],
  ["yellow", "黄色"],
  ["applesauce", "苹果酱"],
  ["hand", "手"],
  ["boat", "船"],
  ["pencil", "铅笔"],
  ["always", "总是"],
  ["telephone", "电话"],
  ["spider", "蜘蛛"],
  ["sometimes", "有时"],
  ["banana", "香蕉"],
  ["frown", "皱眉"],
  ["smile", "微笑"],
  ["paint", "画"],
  ["play", "玩"],
  ["read", "读"],
  ["teacher", "老师"],
  ["write", "写"],
  ["clean", "清洁"],
  ["his", "他的"],
  ["and", "和"],
  ["share", "分享"],
  ["baseball", "棒球"],
  ["house", "房子"],
  ["tag", "捉迷藏"],
  ["hide-and-seek", "捉迷藏"],
  ["dress-up", "装扮"],
  ["car", "汽车"],
  ["train", "火车"],
  ["animal", "动物"],
  ["skates", "溜冰鞋"],
  ["bike", "自行车"],
  ["go", "去"],
  ["lunch", "午餐"],
  ["bird", "鸟"],
  ["bug", "虫子"],
  ["busy", "忙碌"],
  ["toes", "脚趾"],
  ["rose", "玫瑰"],
  ["sniff", "嗅"],
  ["legs", "腿"],
  ["two", "二"],
  ["four", "四"],
  ["six", "六"],
  ["eight", "八"],
  ["ten", "十"],
  ["music", "音乐"],
  ["reading", "阅读"],
  ["math", "数学"],
  ["recess", "课间休息"],
  ["school", "学校"],
  ["science", "科学"],
  ["plant", "植物"],
  ["worm", "蠕虫"],
  ["leaves", "叶子"],
  ["art", "艺术"],
  ["class", "课堂"],
  ["airplane", "飞机"],
  ["hat", "帽子"],
  ["painting", "绘画"],
  ["chain", "链条"],
  ["drawing", "画画"],
  ["mess", "混乱"],
  ["desert", "沙漠"],
  ["lake", "湖"],
  ["mountain", "山"],
  ["river", "河流"],
  ["hill", "小山"],
  ["Earth", "地球"],
  ["tree", "树"],
  ["ball", "球"],
  ["shoes", "鞋"],
  ["blanket", "毯子"],
  ["teddy bear", "泰迪熊"],
  ["aunt", "阿姨"],
  ["brother", "兄弟"],
  ["sister", "姐妹"],
  ["dog", "狗"],
  ["mom", "妈妈"],
  ["dad", "爸爸"],
  ["grandma", "奶奶"],
  ["grandpa", "爷爷"],
  ["heavy", "重"],
  ["stick", "棍子"],
  ["rock", "石头"],
  ["log", "原木"],
  ["lift", "举起"],
  ["light", "轻"],
  ["talk", "说话"],
  ["near", "近"],
  ["lion", "狮子"],
  ["owl", "猫头鹰"],
  ["far", "远"],
  ["wolf", "狼"],
  ["away", "远离"],
  ["pond", "池塘"],
  ["field", "田野"],
  ["farm", "农场"],
  ["mud", "泥"],
  ["barn", "谷仓"],
  ["hay", "干草"],
  ["act", "表演"],
  ["dance", "跳舞"],
  ["sing", "唱歌"],
  ["can", "可以"],
  ["juggle", "杂耍"],
  ["star", "明星"],
  ["bow", "鞠躬"],
  ["fence", "围栏"],
  ["grass", "草"],
  ["swing", "秋千"],
  ["hose", "水管"],
  ["purple", "紫色"],
  ["turtle", "乌龟"],
  ["frog", "青蛙"],
  ["mouse", "老鼠"],
  ["little", "小的"],
  ["get", "得到"],
  ["puppy", "小狗"],
  ["let", "让"],
  ["be", "是"],
  ["snail", "蜗牛"],
  ["beaver", "海狸"],
  ["rainbow", "彩虹"],
  ["umbrella", "伞"],
  ["puddle", "水坑"],
  ["drain", "排水"],
  ["lightning", "闪电"],
  ["wash", "洗"],
  ["new", "新的"],
  ["brush", "刷"],
  ["feed", "喂"],
  ["dry", "干"],
  ["pet", "宠物"],
  ["walk", "走"],
  ["bus", "公交车"],
  ["wait", "等待"],
  ["pay", "支付"],
  ["ride", "骑"],
  ["way", "路"],
  ["crow", "乌鸦"],
  ["mug", "杯子"],
  ["jug", "壶"],
  ["football", "足球"],
  ["game", "游戏"],
  ["friend", "朋友"],
  ["watch", "观看"],
  ["on", "在...上"],
  ["cheer", "欢呼"],
  ["day", "天"],
  ["dress up", "装扮"],
  ["problem", "问题"],
  ["clothes", "衣服"],
  ["stinky", "臭的"],
  ["ate", "吃了"],
  ["forest", "森林"],
  ["moss", "苔藓"],
  ["path", "小路"],
  ["cheese", "奶酪"],
  ["put", "放"],
  ["cookie", "饼干"],
  ["picnic", "野餐"],
  ["sandwich", "三明治"],
  ["chips", "薯片"],
  ["basket", "篮子"],
  ["soda pop", "汽水"],
  ["rest", "休息"],
  ["baby", "婴儿"],
  ["last", "最后"],
  ["grew", "长大"],
  ["flew", "飞了"],
  ["mama", "妈妈"],
  ["brown", "棕色"],
  ["gold", "金色"],
  ["orange", "橙色"],
  ["back", "返回"],
  ["egg", "鸡蛋"],
  ["milk", "牛奶"],
  ["salt", "盐"],
  ["sugar", "糖"],
  ["flour", "面粉"],
  ["butter", "黄油"],
  ["carrot", "胡萝卜"],
  ["crackers", "饼干"],
  ["grapes", "葡萄"],
  ["drink", "饮料"],
  ["pack", "打包"],
  ["feet", "脚"],
  ["elephant", "大象"],
  ["tiger", "老虎"],
  ["shark", "鲨鱼"],
  ["fawn", "小鹿"],
  ["spots", "斑点"],
  ["tiny", "小的"],
  ["smooth", "光滑"],
  ["zebra", "斑马"],
  ["stripes", "条纹"],
  ["fuzzy", "毛茸茸"],
  ["tail", "尾巴"],
  ["person", "人"],
  ["curly", "卷曲的"],
  ["pool", "游泳池"],
  ["sky", "天空"],
  ["ground", "地面"],
  ["father", "父亲"],
  ["bear", "熊"],
  ["fox", "狐狸"],
  ["pot", "锅"],
  ["honey", "蜂蜜"],
  ["scarf", "围巾"],
  ["boots", "靴子"],
  ["mittens", "手套"],
  ["coat", "外套"],
  ["room", "房间"],
  ["bed", "床"],
  ["your", "你的"],
  ["dance", "跳舞"],
  ["run", "跑"],
  ["ride", "骑"],
  ["swing", "秋千"],
  ["slide", "滑梯"],
  ["hike", "远足"],
  ["forward", "向前"],
  ["backward", "向后"],
  ["under", "在...下面"],
  ["over", "在...上面"],
  ["around", "周围"],
  ["across", "穿过"],
]
const defaultWordsC: WordPair[] = [
  ["sister", "姐妹"],
  ["chase", "追逐"],
  ["people", "人"],
  ["swim", "游泳"],
  ["bird", "鸟"],
  ["cold", "冷"],
  ["penguin", "企鹅"],
  ["black", "黑色"],
  ["some", "一些"],
  ["all", "所有"],
  ["are", "是"],
  ["white", "白色"],
  ["egg", "蛋"],
  ["spider", "蜘蛛"],
  ["climb", "爬"],
  ["can", "可以"],
  ["it", "它"],
  ["silk", "丝"],
  ["has", "有"],
  ["eight", "八"],
  ["lay", "产卵"],
  ["country", "国家"],
  ["city", "城市"],
  ["world", "世界"],
  ["state", "州"],
  ["street", "街道"],
  ["home", "家"],
  ["birthday", "生日"],
  ["balloon", "气球"],
  ["bakery", "面包店"],
  ["number", "数字"],
  ["song", "歌曲"],
  ["snack", "零食"],
  ["game", "游戏"],
  ["story", "故事"],
  ["busy", "忙"],
  ["picture", "图片"],
  ["toy", "玩具"],
  ["teeth", "牙齿"],
  ["sharp", "锋利"],
  ["different", "不同"],
  ["shark", "鲨鱼"],
  ["stripes", "条纹"],
  ["spots", "斑点"],
  ["food", "食物"],
  ["fall", "秋天"],
  ["apple", "苹果"],
  ["ripe", "成熟"],
  ["them", "它们"],
  ["pumpkin", "南瓜"],
  ["potato", "土豆"],
  ["pear", "梨"],
  ["beet", "甜菜"],
  ["cabbage", "卷心菜"],
  ["moon", "月亮"],
  ["grass", "草"],
  ["frost", "霜"],
  ["corn", "玉米"],
  ["leaves", "叶子"],
  ["angry", "生气"],
  ["happy", "开心"],
  ["scared", "害怕"],
  ["dog", "狗"],
  ["duck", "鸭子"],
  ["pig", "猪"],
  ["elephant", "大象"],
  ["woman", "女人"],
  ["man", "男人"],
  ["girl", "女孩"],
  ["boy", "男孩"],
  ["in", "在"],
  ["float", "漂浮"],
  ["sail", "航行"],
  ["pedal", "踩踏"],
  ["read", "读"],
  ["play", "玩"],
  ["eat", "吃"],
  ["run", "跑"],
  ["sit", "坐"],
  ["sleep", "睡觉"],
  ["frog", "青蛙"],
  ["tadpole", "蝌蚪"],
  ["tail", "尾巴"],
  ["grow", "长大"],
  ["froglet", "幼蛙"],
  ["legs", "腿"],
  ["smaller", "更小"],
  ["see", "看见"],
  ["two", "二"],
  ["three", "三"],
  ["four", "四"],
  ["five", "五"],
  ["six", "六"],
  ["seven", "七"],
  ["nine", "九"],
  ["many", "很多"],
  ["wheel", "轮子"],
  ["loud", "大声"],
  ["fast", "快"],
  ["slow", "慢"],
  ["silent", "安静"],
  ["meek", "温顺"],
  ["bed", "床"],
  ["under", "在下面"],
  ["closet", "壁橱"],
  ["everywhere", "到处"],
  ["toy box", "玩具箱"],
  ["wonder", "想知道"],
  ["sheep", "羊"],
  ["lots", "很多"],
  ["purr", "呼噜声"],
  ["wool", "羊毛"],
  ["scary", "可怕"],
  ["mask", "面具"],
  ["beef", "牛肉"],
  ["turkey", "火鸡"],
  ["chicken", "鸡肉"],
  ["same", "相同"],
  ["pork", "猪肉"],
  ["crash", "碰撞"],
  ["plop", "扑通声"],
  ["rip", "撕裂"],
  ["freeze", "冻结"],
  ["wash", "洗"],
  ["machine", "机器"],
  ["make", "制造"],
  ["blender", "搅拌机"],
  ["dry", "干"],
  ["salt", "盐"],
  ["onion", "洋葱"],
  ["tomato", "番茄"],
  ["chips", "薯片"],
  ["salad", "沙拉"],
  ["cilantro", "香菜"],
  ["pepper", "胡椒"],
  ["lemon juice", "柠檬汁"],
  ["peel", "剥皮"],
  ["mash", "捣碎"],
  ["count", "数"],
  ["boil", "煮沸"],
  ["lunch", "午餐"],
  ["try", "尝试"],
  ["hide", "躲"],
  ["grandma", "奶奶"],
  ["nice", "友好"],
  ["fort", "堡垒"],
  ["airplane", "飞机"],
  ["thing", "东西"],
  ["drum", "鼓"],
  ["bucket", "桶"],
  ["puppet", "木偶"],
  ["sprinkler", "洒水器"],
  ["phone", "电话"],
  ["book", "书"],
  ["close", "关闭"],
  ["window", "窗户"],
  ["box", "盒子"],
  ["open", "打开"],
  ["cage", "笼子"],
  ["drawer", "抽屉"],
  ["jar", "罐子"],
  ["wings", "翅膀"],
  ["shoes", "鞋"],
  ["gloves", "手套"],
  ["twins", "双胞胎"],
  ["socks", "袜子"],
  ["skates", "溜冰鞋"],
  ["pair", "一对"],
  ["dice", "骰子"],
  ["one", "一"],
  ["eye", "眼睛"],
  ["stone", "石头"],
  ["mountain", "山"],
  ["sand", "沙子"],
  ["boulder", "巨石"],
  ["pebble", "卵石"],
  ["dust", "灰尘"],
  ["wonderful", "美妙"],
  ["shy", "害羞"],
  ["proud", "自豪"],
  ["grand", "壮丽"],
  ["fancy", "精致"],
  ["sure", "确定"],
  ["comet", "彗星"],
  ["planet", "行星"],
  ["space", "空间"],
  ["day", "白天"],
  ["night", "晚上"],
  ["star", "星星"],
  ["sky", "天空"],
  ["satellite", "卫星"],
  ["Moon", "月亮"],
  ["drink", "喝"],
  ["first", "第一"],
  ["slide", "滑动"],
  ["turn", "转"],
  ["cut out", "剪下"],
  ["minute", "分钟"],
  ["twice", "两次"],
  ["bottom", "底部"],
  ["top", "顶部"],
  ["front", "前面"],
  ["my", "我的"],
  ["brush", "刷"],
  ["toothpaste", "牙膏"],
  ["back", "后面"],
  ["wolf", "狼"],
  ["eagle", "鹰"],
  ["goose", "鹅"],
  ["beaver", "海狸"],
  ["moose", "驼鹿"],
  ["loon", "潜鸟"],
  ["big", "大"],
  ["small", "小"],
  ["rake", "耙子"],
  ["I", "我"],
  ["leaves", "叶子"],
  ["brown", "棕色"],
  ["gold", "金色"],
  ["orange", "橙色"],
  ["find", "找到"],
  ["swing", "秋千"],
  ["pot", "锅"],
  ["Easter", "复活节"],
  ["jam", "果酱"],
  ["horn", "喇叭"],
  ["banjo", "班卓琴"],
  ["fiddle", "小提琴"],
  ["fife", "长笛"],
  ["write", "写"],
  ["cut", "切"],
  ["carry", "携带"],
  ["dig", "挖"],
  ["pound", "捣碎"],
  ["ant", "蚂蚁"],
  ["butterfly", "蝴蝶"],
  ["ladybug", "瓢虫"],
  ["flea", "跳蚤"],
  ["cricket", "蟋蟀"],
  ["beetle", "甲虫"],
  ["mouth", "嘴"],
  ["nose", "鼻子"],
  ["eyes", "眼睛"],
  ["house", "房子"],
  ["arm", "手臂"],
  ["snowman", "雪人"],
  ["breakfast", "早餐"],
  ["yogurt", "酸奶"],
  ["toast", "吐司"],
  ["bacon", "培根"],
  ["muffin", "松饼"],
  ["cereal", "麦片"],
  ["art", "艺术"],
  ["teacher", "老师"],
  ["job", "工作"],
  ["boss", "老板"],
  ["women", "女人"],
  ["seed", "种子"],
  ["bug", "虫子"],
  ["watch", "看"],
  ["shirt", "衬衫"],
  ["smile", "微笑"],
  ["ring", "戒指"],
  ["love", "爱"],
  ["bear", "熊"],
  ["lion", "狮子"],
  ["tiger", "老虎"],
  ["monkey", "猴子"],
  ["dinosaur", "恐龙"],
  ["giraffe", "长颈鹿"],
  ["hippopotamus", "河马"],
  ["sea lion", "海狮"],
  ["teach", "教"],
  ["something", "某物"],
  ["want", "想要"],
  ["dream", "梦想"],
  ["blink", "眨眼"],
  ["light", "光"],
  ["nighttime", "夜晚"],
  ["shine", "闪耀"],
  ["rise", "升起"],
  ["sing", "唱歌"],
  ["hunt", "打猎"],
  ["cookie", "饼干"],
  ["peas", "豌豆"],
  ["banana", "香蕉"],
  ["carrot", "胡萝卜"],
  ["popcorn", "爆米花"],
  ["pizza", "披萨"],
  ["lima beans", "利马豆"],
  ["corn on the cob", "玉米棒"],
]
const defaultWordsFry: WordPair[] = [
  ["a", "一个"],
  ["about", "关于"],
  ["all", "所有"],
  ["am", "是"],
  ["an", "一个"],
  ["and", "和"],
  ["are", "是"],
  ["as", "作为"],
  ["at", "在"],
  ["be", "是"],
  ["been", "已经"],
  ["but", "但是"],
  ["by", "通过"],
  ["called", "被称为"],
  ["can", "能"],
  ["come", "来"],
  ["could", "可以"],
  ["day", "天"],
  ["did", "做了"],
  ["do", "做"],
  ["down", "向下"],
  ["each", "每个"],
  ["find", "找到"],
  ["first", "第一"],
  ["for", "为了"],
  ["from", "从"],
  ["get", "得到"],
  ["go", "去"],
  ["had", "有"],
  ["has", "有"],
  ["have", "有"],
  ["he", "他"],
  ["her", "她"],
  ["him", "他"],
  ["his", "他的"],
  ["how", "如何"],
  ["I", "我"],
  ["if", "如果"],
  ["in", "在...里面"],
  ["into", "进入"],
  ["is", "是"],
  ["it", "它"],
  ["its", "它的"],
  ["like", "喜欢"],
  ["long", "长的"],
  ["look", "看"],
  ["made", "制作"],
  ["make", "制作"],
  ["many", "许多"],
  ["may", "也许"],
  ["more", "更多"],
  ["my", "我的"],
  ["no", "不"],
  ["not", "不"],
  ["now", "现在"],
  ["number", "数字"],
  ["of", "的"],
  ["on", "在...上面"],
  ["one", "一"],
  ["or", "或者"],
  ["other", "其他"],
  ["out", "出去"],
  ["part", "部分"],
  ["people", "人们"],
  ["said", "说"],
  ["see", "看"],
  ["she", "她"],
  ["so", "所以"],
  ["some", "一些"],
  ["than", "比"],
  ["that", "那个"],
  ["the", "这个"],
  ["their", "他们的"],
  ["them", "他们"],
  ["then", "然后"],
  ["there", "那里"],
  ["these", "这些"],
  ["they", "他们"],
  ["this", "这个"],
  ["time", "时间"],
  ["to", "到"],
  ["two", "二"],
  ["up", "向上"],
  ["use", "使用"],
  ["was", "是"],
  ["water", "水"],
  ["way", "方式"],
  ["we", "我们"],
  ["were", "是"],
  ["what", "什么"],
  ["when", "当...时"],
  ["which", "哪个"],
  ["who", "谁"],
  ["will", "将要"],
  ["with", "和"],
  ["words", "单词"],
  ["would", "会"],
  ["write", "写"],
  ["you", "你"],
  ["your", "你的"],
  ["after", "之后"],
  ["again", "再次"],
  ["air", "空气"],
  ["also", "也"],
  ["America", "美国"],
  ["animal", "动物"],
  ["another", "另一个"],
  ["answer", "回答"],
  ["any", "任何"],
  ["around", "周围"],
  ["ask", "问"],
  ["away", "离开"],
  ["back", "后面"],
  ["because", "因为"],
  ["before", "之前"],
  ["big", "大"],
  ["boy", "男孩"],
  ["came", "来"],
  ["change", "改变"],
  ["different", "不同的"],
  ["does", "做"],
  ["end", "结束"],
  ["even", "甚至"],
  ["follow", "跟随"],
  ["form", "形式"],
  ["found", "找到"],
  ["give", "给"],
  ["good", "好"],
  ["great", "伟大"],
  ["hand", "手"],
  ["help", "帮助"],
  ["here", "这里"],
  ["home", "家"],
  ["house", "房子"],
  ["just", "只是"],
  ["kind", "种类"],
  ["know", "知道"],
  ["land", "土地"],
  ["large", "大"],
  ["learn", "学习"],
  ["letter", "字母"],
  ["line", "线"],
  ["little", "小"],
  ["live", "活"],
  ["man", "人"],
  ["me", "我"],
  ["means", "意思"],
  ["men", "男人"],
  ["most", "最多"],
  ["mother", "母亲"],
  ["move", "移动"],
  ["much", "很多"],
  ["must", "必须"],
  ["name", "名字"],
  ["need", "需要"],
  ["new", "新"],
  ["off", "离开"],
  ["old", "老"],
  ["only", "只"],
  ["our", "我们的"],
  ["over", "超过"],
  ["page", "页面"],
  ["picture", "图片"],
  ["place", "地方"],
  ["play", "玩"],
  ["point", "点"],
  ["put", "放"],
  ["read", "读"],
  ["right", "正确"],
  ["same", "相同"],
  ["say", "说"],
  ["sentence", "句子"],
  ["set", "设置"],
  ["should", "应该"],
  ["show", "展示"],
  ["small", "小"],
  ["sound", "声音"],
  ["spell", "拼写"],
  ["still", "仍然"],
  ["study", "学习"],
  ["such", "这样"],
  ["take", "拿"],
  ["tell", "告诉"],
  ["things", "事情"],
  ["think", "思考"],
  ["three", "三"],
  ["through", "通过"],
  ["too", "也"],
  ["try", "尝试"],
  ["turn", "转弯"],
  ["us", "我们"],
  ["very", "非常"],
  ["want", "想要"],
  ["well", "好"],
  ["went", "去了"],
  ["where", "哪里"],
  ["why", "为什么"],
  ["work", "工作"],
  ["world", "世界"],
  ["years", "年"],
  ["above", "上方"],
  ["add", "添加"],
  ["almost", "几乎"],
  ["along", "沿着"],
  ["always", "总是"],
  ["began", "开始"],
  ["begin", "开始"],
  ["being", "正在"],
  ["below", "下方"],
  ["between", "之间"],
  ["book", "书"],
  ["both", "两者"],
  ["car", "汽车"],
  ["carry", "携带"],
  ["children", "儿童"],
  ["city", "城市"],
  ["close", "关闭"],
  ["country", "国家"],
  ["cut", "剪"],
  ["don’t", "不要"],
  ["earth", "地球"],
  ["eat", "吃"],
  ["enough", "足够"],
  ["every", "每个"],
  ["example", "例子"],
  ["eyes", "眼睛"],
  ["face", "脸"],
  ["family", "家庭"],
  ["far", "远"],
  ["father", "父亲"],
  ["feet", "脚"],
  ["few", "少数"],
  ["food", "食物"],
  ["four", "四"],
  ["girl", "女孩"],
  ["got", "得到"],
  ["group", "团体"],
  ["grow", "成长"],
  ["hard", "难"],
  ["head", "头"],
  ["hear", "听"],
  ["high", "高"],
  ["idea", "主意"],
  ["important", "重要"],
  ["Indian", "印度的"],
  ["it’s", "它是"],
  ["keep", "保持"],
  ["last", "最后"],
  ["late", "晚"],
  ["leave", "离开"],
  ["left", "左边"],
  ["let", "让"],
  ["life", "生命"],
  ["light", "光"],
  ["list", "列表"],
  ["might", "可能"],
  ["mile", "英里"],
  ["miss", "想念"],
  ["mountains", "山脉"],
  ["near", "近"],
  ["never", "从不"],
  ["next", "下一个"],
  ["night", "夜晚"],
  ["often", "经常"],
  ["once", "一次"],
  ["open", "打开"],
  ["own", "自己的"],
  ["paper", "纸"],
  ["plant", "植物"],
  ["real", "真实"],
  ["river", "河流"],
  ["run", "跑"],
  ["saw", "看见"],
  ["school", "学校"],
  ["sea", "海"],
  ["second", "秒"],
  ["seem", "似乎"],
  ["side", "边"],
  ["something", "某物"],
  ["sometimes", "有时"],
  ["song", "歌曲"],
  ["soon", "很快"],
  ["start", "开始"],
  ["state", "州"],
  ["stop", "停止"],
  ["story", "故事"],
  ["talk", "谈话"],
  ["those", "那些"],
  ["thought", "想法"],
  ["together", "一起"],
  ["took", "拿"],
  ["tree", "树"],
  ["under", "在...下面"],
  ["until", "直到"],
  ["walk", "走路"],
  ["watch", "看"],
  ["while", "当...时"],
  ["white", "白色"],
  ["without", "没有"],
  ["young", "年轻"],
  ["across", "穿过"],
  ["against", "对抗"],
  ["area", "区域"],
  ["become", "成为"],
  ["best", "最好"],
  ["better", "更好"],
  ["birds", "鸟类"],
  ["black", "黑色"],
  ["body", "身体"],
  ["certain", "一定"],
  ["cold", "冷"],
  ["color", "颜色"],
  ["complete", "完成"],
  ["covered", "覆盖"],
  ["cried", "哭了"],
  ["didn’t", "没有"],
  ["dog", "狗"],
  ["door", "门"],
  ["draw", "画"],
  ["during", "期间"],
  ["early", "早"],
  ["easy", "容易"],
  ["ever", "曾经"],
  ["fall", "秋天"],
  ["farm", "农场"],
  ["fast", "快"],
  ["field", "田野"],
  ["figure", "数字"],
  ["fire", "火"],
  ["fish", "鱼"],
  ["five", "五"],
  ["friends", "朋友"],
  ["ground", "地面"],
  ["happened", "发生"],
  ["heard", "听到"],
  ["himself", "他自己"],
  ["hold", "拿着"],
  ["horse", "马"],
  ["hours", "小时"],
  ["however", "然而"],
  ["hundred", "一百"],
  ["I’ll", "我将"],
  ["king", "国王"],
  ["knew", "知道"],
  ["listen", "听"],
  ["low", "低"],
  ["map", "地图"],
  ["mark", "标记"],
  ["measure", "测量"],
  ["money", "钱"],
  ["morning", "早上"],
  ["music", "音乐"],
  ["north", "北"],
  ["notice", "注意"],
  ["numerall", "数字的"],
  ["order", "顺序"],
  ["passed", "通过"],
  ["pattern", "图案"],
  ["piece", "一块"],
  ["plan", "计划"],
  ["problem", "问题"],
  ["products", "产品"],
  ["pulled", "拉"],
  ["questions", "问题"],
  ["reached", "到达"],
  ["red", "红色"],
  ["remember", "记住"],
  ["rock", "岩石"],
  ["room", "房间"],
  ["seen", "看见"],
  ["several", "几个"],
  ["ship", "船"],
  ["short", "短"],
  ["since", "自从"],
  ["sing", "唱歌"],
  ["slowly", "慢慢地"],
  ["south", "南"],
  ["space", "空间"],
  ["stand", "站"],
  ["step", "步骤"],
  ["sun", "太阳"],
  ["sure", "确定"],
  ["table", "桌子"],
  ["today", "今天"],
  ["told", "告诉"],
  ["top", "顶部"],
  ["toward", "向"],
  ["town", "城镇"],
  ["travel", "旅行"],
  ["true", "真实"],
  ["unit", "单位"],
  ["upon", "在...上面"],
  ["usually", "通常"],
  ["voice", "声音"],
  ["vowel", "元音"],
  ["war", "战争"],
  ["waves", "波浪"],
  ["whole", "整个"],
  ["wind", "风"],
  ["wood", "木头"],
  ["able", "能够"],
  ["ago", "以前"],
  ["among", "在...之间"],
  ["ball", "球"],
  ["base", "基地"],
  ["became", "成为"],
  ["behind", "后面"],
  ["boat", "船"],
  ["box", "盒子"],
  ["bread", "面包"],
  ["bring", "带来"],
  ["brought", "带来"],
  ["building", "建筑物"],
  ["built", "建造"],
  ["cannot", "不能"],
  ["carefully", "小心地"],
  ["check", "检查"],
  ["circle", "圆形"],
  ["class", "班级"],
  ["clear", "清楚"],
  ["common", "常见"],
  ["contain", "包含"],
  ["correct", "正确"],
  ["course", "课程"],
  ["dark", "黑暗"],
  ["decided", "决定"],
  ["deep", "深"],
  ["done", "完成"],
  ["dry", "干"],
  ["English", "英语"],
  ["equation", "方程"],
  ["explain", "解释"],
  ["fact", "事实"],
  ["feel", "感觉"],
  ["filled", "充满"],
  ["finally", "最后"],
  ["fine", "好"],
  ["fly", "飞"],
  ["force", "力量"],
  ["front", "前面"],
  ["full", "满"],
  ["game", "游戏"],
  ["gave", "给"],
  ["government", "政府"],
  ["green", "绿色"],
  ["half", "一半"],
  ["heat", "热量"],
  ["heavy", "重"],
  ["hot", "热"],
  ["inches", "英寸"],
  ["include", "包括"],
  ["inside", "里面"],
  ["island", "岛屿"],
  ["known", "知道"],
  ["language", "语言"],
  ["less", "更少"],
  ["machine", "机器"],
  ["material", "材料"],
  ["minutes", "分钟"],
  ["note", "笔记"],
  ["nothing", "没有"],
  ["noun", "名词"],
  ["object", "物体"],
  ["ocean", "海洋"],
  ["oh", "哦"],
  ["pair", "一对"],
  ["person", "人"],
  ["plane", "飞机"],
  ["power", "力量"],
  ["produce", "生产"],
  ["quickly", "快速地"],
  ["ran", "跑"],
  ["rest", "休息"],
  ["road", "路"],
  ["round", "圆形"],
  ["rule", "规则"],
  ["scientists", "科学家"],
  ["shape", "形状"],
  ["shown", "显示"],
  ["six", "六"],
  ["size", "大小"],
  ["special", "特殊"],
  ["stars", "星星"],
  ["stay", "停留"],
  ["stood", "站"],
  ["street", "街道"],
  ["strong", "强大"],
  ["surface", "表面"],
  ["system", "系统"],
  ["ten", "十"],
  ["though", "虽然"],
  ["thousands", "成千上万"],
  ["understand", "理解"],
  ["verb", "动词"],
  ["wait", "等待"],
  ["warm", "温暖"],
  ["week", "周"],
  ["wheels", "轮子"],
  ["yes", "是"],
  ["yet", "仍然"],
  ["anything", "任何事"],
  ["arms", "手臂"],
  ["beautiful", "美丽"],
  ["believe", "相信"],
  ["beside", "旁边"],
  ["bill", "账单"],
  ["blue", "蓝色"],
  ["brother", "兄弟"],
  ["can’t", "不能"],
  ["cause", "原因"],
  ["cells", "细胞"],
  ["center", "中心"],
  ["clothes", "衣服"],
  ["dance", "跳舞"],
  ["describe", "描述"],
  ["developed", "发展"],
  ["difference", "差异"],
  ["direction", "方向"],
  ["discovered", "发现"],
  ["distance", "距离"],
  ["divided", "划分"],
  ["drive", "驾驶"],
  ["drop", "下降"],
  ["edge", "边缘"],
  ["eggs", "鸡蛋"],
  ["energy", "能量"],
  ["Europe", "欧洲"],
  ["exercise", "锻炼"],
  ["farmers", "农民"],
  ["felt", "感觉"],
  ["finished", "完成"],
  ["flowers", "花朵"],
  ["forest", "森林"],
  ["general", "一般"],
  ["gone", "离开"],
  ["grass", "草"],
  ["happy", "快乐"],
  ["heart", "心"],
  ["held", "举行"],
  ["instruments", "乐器"],
  ["interest", "兴趣"],
  ["job", "工作"],
  ["kept", "保持"],
  ["lay", "放置"],
  ["legs", "腿"],
  ["length", "长度"],
  ["love", "爱"],
  ["main", "主要"],
  ["matter", "物质"],
  ["meet", "见面"],
  ["members", "成员"],
  ["million", "百万"],
  ["mind", "思想"],
  ["months", "月"],
  ["moon", "月亮"],
  ["paint", "绘画"],
  ["paragraph", "段落"],
  ["past", "过去"],
  ["perhaps", "也许"],
  ["picked", "选择"],
  ["present", "现在"],
  ["probably", "可能"],
  ["race", "比赛"],
  ["rain", "雨"],
  ["raised", "提升"],
  ["ready", "准备好"],
  ["reason", "原因"],
  ["record", "记录"],
  ["region", "地区"],
  ["represent", "代表"],
  ["return", "返回"],
  ["root", "根"],
  ["sat", "坐"],
  ["shall", "将"],
  ["sign", "符号"],
  ["simple", "简单"],
  ["site", "地点"],
  ["sky", "天空"],
  ["soft", "柔软"],
  ["square", "正方形"],
  ["store", "商店"],
  ["subject", "主题"],
  ["suddenly", "突然"],
  ["sum", "总和"],
  ["summer", "夏天"],
  ["syllables", "音节"],
  ["teacher", "老师"],
  ["test", "测验"],
  ["third", "第三"],
  ["train", "火车"],
  ["wall", "墙"],
  ["weather", "天气"],
  ["west", "西方"],
  ["whether", "是否"],
  ["wide", "宽"],
  ["wild", "野生"],
  ["window", "窗户"],
  ["winter", "冬天"],
  ["wish", "愿望"],
  ["written", "书写"],
  ["act", "行为"],
  ["Africa", "非洲"],
  ["age", "年龄"],
  ["already", "已经"],
  ["although", "虽然"],
  ["amount", "数量"],
  ["angle", "角度"],
  ["appear", "出现"],
  ["baby", "婴儿"],
  ["bear", "熊"],
  ["beat", "打败"],
  ["bed", "床"],
  ["bottom", "底部"],
  ["bright", "明亮"],
  ["broken", "破碎"],
  ["build", "建造"],
  ["buy", "购买"],
  ["care", "关心"],
  ["case", "案例"],
  ["cat", "猫"],
  ["century", "世纪"],
  ["consonant", "辅音"],
  ["copy", "复制"],
  ["couldn’t", "不会"],
  ["count", "计数"],
  ["cross", "交叉"],
  ["dictionary", "词典"],
  ["died", "死亡"],
  ["dress", "连衣裙"],
  ["either", "或者"],
  ["everyone", "每个人"],
  ["everything", "一切"],
  ["exactly", "准确地"],
  ["factors", "因素"],
  ["fight", "打架"],
  ["fingers", "手指"],
  ["floor", "地板"],
  ["fraction", "分数"],
  ["free", "自由"],
  ["French", "法语"],
  ["gold", "黄金"],
  ["hair", "头发"],
  ["hill", "山丘"],
  ["hole", "洞"],
  ["hope", "希望"],
  ["ice", "冰"],
  ["instead", "代替"],
  ["iron", "铁"],
  ["jumped", "跳"],
  ["killed", "杀死"],
  ["lake", "湖"],
  ["laughed", "笑"],
  ["lead", "领导"],
  ["let’s", "让我们"],
  ["lot", "很多"],
  ["melody", "旋律"],
  ["metal", "金属"],
  ["method", "方法"],
  ["middle", "中间"],
  ["milk", "牛奶"],
  ["moment", "时刻"],
  ["nation", "国家"],
  ["natural", "自然"],
  ["outside", "外面"],
  ["per", "每"],
  ["phrase", "短语"],
  ["poor", "贫穷"],
  ["possible", "可能"],
  ["pounds", "磅"],
  ["pushed", "推"],
  ["quiet", "安静"],
  ["quite", "相当"],
  ["remain", "保持"],
  ["result", "结果"],
  ["ride", "骑"],
  ["rolled", "滚动"],
  ["sail", "航行"],
  ["scale", "规模"],
  ["section", "部分"],
  ["sleep", "睡觉"],
  ["smiled", "微笑"],
  ["snow", "雪"],
  ["soil", "土壤"],
  ["solve", "解决"],
  ["someone", "某人"],
  ["son", "儿子"],
  ["speak", "说"],
  ["speed", "速度"],
  ["spring", "春天"],
  ["stone", "石头"],
  ["surprise", "惊喜"],
  ["tall", "高"],
  ["temperature", "温度"],
  ["themselves", "他们自己"],
  ["tiny", "微小"],
  ["trip", "旅行"],
  ["type", "类型"],
  ["village", "村庄"],
  ["within", "在...之内"],
  ["wonder", "奇迹"],
  ["alone", "独自"],
  ["art", "艺术"],
  ["bad", "坏"],
  ["bank", "银行"],
  ["bit", "一点"],
  ["break", "打破"],
  ["brown", "棕色"],
  ["burning", "燃烧"],
  ["business", "商业"],
  ["captain", "船长"],
  ["catch", "抓住"],
  ["caught", "抓住"],
  ["cents", "美分"],
  ["child", "孩子"],
  ["choose", "选择"],
  ["clean", "干净"],
  ["climbed", "爬"],
  ["cloud", "云"],
  ["coast", "海岸"],
  ["continued", "继续"],
  ["control", "控制"],
  ["cool", "凉爽"],
  ["cost", "成本"],
  ["decimal", "小数"],
  ["desert", "沙漠"],
  ["design", "设计"],
  ["direct", "直接"],
  ["drawing", "绘画"],
  ["ears", "耳朵"],
  ["east", "东"],
  ["else", "其他"],
  ["engine", "发动机"],
  ["England", "英格兰"],
  ["equal", "相等"],
  ["experiment", "实验"],
  ["express", "表达"],
  ["feeling", "感觉"],
  ["fell", "掉落"],
  ["flow", "流动"],
  ["foot", "脚"],
  ["garden", "花园"],
  ["gas", "气体"],
  ["glass", "玻璃"],
  ["God", "上帝"],
  ["grew", "生长"],
  ["history", "历史"],
  ["human", "人类"],
  ["hunting", "打猎"],
  ["increase", "增加"],
  ["information", "信息"],
  ["itself", "它自己"],
  ["joined", "加入"],
  ["key", "钥匙"],
  ["lady", "女士"],
  ["law", "法律"],
  ["least", "最少"],
  ["lost", "迷失"],
  ["maybe", "也许"],
  ["mouth", "嘴"],
  ["party", "聚会"],
  ["pay", "支付"],
  ["period", "时期"],
  ["plains", "平原"],
  ["please", "请"],
  ["practice", "练习"],
  ["president", "总统"],
  ["received", "收到"],
  ["report", "报告"],
  ["ring", "戒指"],
  ["rise", "上升"],
  ["row", "行"],
  ["save", "保存"],
  ["seeds", "种子"],
  ["sent", "发送"],
  ["separate", "分离"],
  ["serve", "服务"],
  ["shouted", "喊叫"],
  ["single", "单个"],
  ["skin", "皮肤"],
  ["statement", "声明"],
  ["stick", "棍子"],
  ["straight", "直"],
  ["strange", "奇怪"],
  ["students", "学生"],
  ["suppose", "假设"],
  ["symbols", "符号"],
  ["team", "团队"],
  ["touch", "触摸"],
  ["trouble", "麻烦"],
  ["uncle", "叔叔"],
  ["valley", "山谷"],
  ["visit", "访问"],
  ["wear", "穿"],
  ["whose", "谁的"],
  ["wire", "电线"],
  ["woman", "女人"],
  ["wrote", "写"],
  ["yard", "院子"],
  ["you’re", "你是"],
  ["yourself", "你自己"],
  ["addition", "加法"],
  ["army", "军队"],
  ["bell", "铃铛"],
  ["belong", "属于"],
  ["block", "块"],
  ["blood", "血液"],
  ["blow", "吹"],
  ["board", "板"],
  ["bones", "骨头"],
  ["branches", "树枝"],
  ["cattle", "牛"],
  ["chief", "首领"],
  ["compare", "比较"],
  ["compound", "复合"],
  ["consider", "考虑"],
  ["cook", "烹饪"],
  ["corner", "角落"],
  ["crops", "庄稼"],
  ["crowd", "人群"],
  ["current", "当前"],
  ["doctor", "医生"],
  ["dollars", "美元"],
  ["eight", "八"],
  ["electric", "电动的"],
  ["elements", "元素"],
  ["enjoy", "享受"],
  ["entered", "进入"],
  ["except", "除了"],
  ["exciting", "激动人心"],
  ["expect", "期待"],
  ["famous", "著名"],
  ["fit", "适合"],
  ["flat", "平坦"],
  ["fruit", "水果"],
  ["fun", "乐趣"],
  ["guess", "猜"],
  ["hat", "帽子"],
  ["hit", "打"],
  ["indicate", "指出"],
  ["industry", "工业"],
  ["insects", "昆虫"],
  ["interesting", "有趣"],
  ["Japanese", "日本人"],
  ["lie", "躺"],
  ["lifted", "举起"],
  ["loud", "大声"],
  ["major", "主要"],
  ["mall", "购物中心"],
  ["meat", "肉"],
  ["mine", "我的"],
  ["modern", "现代"],
  ["movement", "运动"],
  ["necessary", "必要"],
  ["observe", "观察"],
  ["park", "公园"],
  ["particular", "特定的"],
  ["planets", "行星"],
  ["poem", "诗"],
  ["pole", "杆"],
  ["position", "位置"],
  ["process", "过程"],
  ["property", "财产"],
  ["provide", "提供"],
  ["rather", "宁愿"],
  ["rhythm", "韵律"],
  ["rich", "富有"],
  ["safe", "安全"],
  ["sand", "沙子"],
  ["science", "科学"],
  ["sell", "卖"],
  ["send", "发送"],
  ["sense", "感觉"],
  ["seven", "七"],
  ["sharp", "锋利"],
  ["shoulder", "肩膀"],
  ["sight", "视力"],
  ["silent", "沉默"],
  ["soldiers", "士兵"],
  ["spot", "地点"],
  ["spread", "传播"],
  ["stream", "溪流"],
  ["string", "绳子"],
  ["suggested", "建议"],
  ["supply", "供应"],
  ["swim", "游泳"],
  ["terms", "条款"],
  ["thick", "厚"],
  ["thin", "薄"],
  ["thus", "因此"],
  ["tied", "系"],
  ["tone", "音调"],
  ["trade", "贸易"],
  ["tube", "管"],
  ["value", "价值"],
  ["wash", "洗"],
  ["wasn’t", "不是"],
  ["weight", "重量"],
  ["wife", "妻子"],
  ["wings", "翅膀"],
  ["won’t", "不会"],
  ["action", "行动"],
  ["actually", "实际上"],
  ["adjective", "形容词"],
  ["afraid", "害怕"],
  ["agreed", "同意"],
  ["ahead", "向前"],
  ["allow", "允许"],
  ["apple", "苹果"],
  ["arrived", "到达"],
  ["born", "出生"],
  ["bought", "购买"],
  ["British", "英国的"],
  ["capital", "首都"],
  ["chance", "机会"],
  ["chart", "图表"],
  ["church", "教堂"],
  ["column", "列"],
  ["company", "公司"],
  ["conditions", "条件"],
  ["corn", "玉米"],
  ["cotton", "棉花"],
  ["cows", "奶牛"],
  ["create", "创造"],
  ["dead", "死亡"],
  ["deal", "交易"],
  ["death", "死亡"],
  ["details", "细节"],
  ["determine", "决定"],
  ["difficult", "困难"],
  ["division", "除法"],
  ["doesn’t", "不"],
  ["effect", "效果"],
  ["entire", "整个"],
  ["especially", "尤其"],
  ["evening", "傍晚"],
  ["experience", "经验"],
  ["factories", "工厂"],
  ["fair", "公平"],
  ["fear", "恐惧"],
  ["fig", "无花果"],
  ["forward", "向前"],
  ["France", "法国"],
  ["fresh", "新鲜"],
  ["Greek", "希腊的"],
  ["gun", "枪"],
  ["hoe", "锄头"],
  ["huge", "巨大"],
  ["isn’t", "不是"],
  ["led", "领导"],
  ["level", "水平"],
  ["located", "位于"],
  ["march", "三月"],
  ["match", "匹配"],
  ["molecules", "分子"],
  ["northern", "北方的"],
  ["nose", "鼻子"],
  ["office", "办公室"],
  ["opposite", "相反"],
  ["oxygen", "氧气"],
  ["plural", "复数"],
  ["prepared", "准备"],
  ["pretty", "漂亮"],
  ["printed", "打印"],
  ["radio", "收音机"],
  ["repeated", "重复"],
  ["rope", "绳子"],
  ["rose", "玫瑰"],
  ["score", "分数"],
  ["seat", "座位"],
  ["settled", "安顿"],
  ["shoes", "鞋子"],
  ["shop", "商店"],
  ["similar", "相似"],
  ["sir", "先生"],
  ["sister", "姐妹"],
  ["smell", "闻"],
  ["solution", "解决方案"],
  ["southern", "南方的"],
  ["steel", "钢铁"],
  ["stretched", "伸展"],
  ["substances", "物质"],
  ["suffix", "后缀"],
  ["sugar", "糖"],
  ["tools", "工具"],
  ["total", "总计"],
  ["track", "轨道"],
  ["triangle", "三角形"],
  ["truck", "卡车"],
  ["underline", "下划线"],
  ["various", "各种各样"],
  ["view", "视图"],
  ["Washington", "华盛顿"],
  ["we’ll", "我们将"],
  ["western", "西方的"],
  ["win", "赢"],
  ["women", "女性"],
  ["workers", "工人"],
  ["wouldn’t", "不会"],
  ["wrong", "错误"],
  ["yellow", "黄色"],
]

const builtInLists: WordLists = {
  "word-a.json": defaultWordsA,
  "word-aa.json": defaultWordsAA,
  "word-b.json": defaultWordsB,
  "word-c.json": defaultWordsC,
  "Fry Word Lists.json": defaultWordsFry,
}

const cardColors = [
  "bg-red-500",
  "bg-green-500",
  "bg-blue-500",
  "bg-yellow-500",
  "bg-purple-500",
  "bg-orange-500",
  "bg-teal-500",
  "bg-pink-500",
  "bg-indigo-500",
  "bg-lime-500",
]

const shuffleArray = <T,>(array: T[]): T[] => {
  const newArray = [...array]
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[newArray[i], newArray[j]] = [newArray[j], newArray[i]]
  }
  return newArray
}

export default function WordMatchGame() {
  const [title, setTitle] = useState("Word Match")
  const [availableLists, setAvailableLists] = useState<WordLists>(builtInLists)
  const [currentListName, setCurrentListName] = useState("word-a.json")
  const [pairCount, setPairCount] = useState(10)
  const [gameBoard, setGameBoard] = useState<GameCard[]>([])
  const [gameState, setGameState] = useState<GameState>("idle")
  const [timeElapsed, setTimeElapsed] = useState(0)
  const [firstSelection, setFirstSelection] = useState<GameCard | null>(null)
  const [isChecking, setIsChecking] = useState(false)
  const [currentWordIndex, setCurrentWordIndex] = useState(0)
  const [showModal, setShowModal] = useState(false)
  const [notification, setNotification] = useState("")
  const [isFocusMode, setIsFocusMode] = useState(false)

  const fileInputRef = useRef<HTMLInputElement>(null)
  const timerRef = useRef<NodeJS.Timeout | null>(null)
  const successSoundRef = useRef<HTMLAudioElement>(null)

  useEffect(() => {
    const savedTitle = localStorage.getItem("wordMatchTitle")
    if (savedTitle) setTitle(savedTitle)

    try {
      const savedLists = localStorage.getItem("wordMatchUserLists")
      const userLists = savedLists ? JSON.parse(savedLists) : {}
      setAvailableLists({ ...builtInLists, ...userLists })
    } catch (e) {
      console.error("Failed to parse user lists from localStorage", e)
      setAvailableLists(builtInLists)
    }

    const lastSelected = localStorage.getItem("wordMatchLastSelected")
    if (
      lastSelected &&
      (builtInLists[lastSelected] || (localStorage.getItem("wordMatchUserLists") || "{}").includes(lastSelected))
    ) {
      setCurrentListName(lastSelected)
    } else {
      setCurrentListName(Object.keys(builtInLists)[0])
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("wordMatchTitle", title)
  }, [title])

  useEffect(() => {
    const wordList = availableLists[currentListName] || []
    if (wordList.length > 0 && gameState !== "playing") {
      prepareNewRound(currentWordIndex, pairCount, false, wordList)
    } else if (wordList.length === 0) {
      generatePlaceholderBoard(pairCount)
    }
  }, [availableLists, currentListName, pairCount])

  useEffect(() => {
    localStorage.setItem("wordMatchLastSelected", currentListName)
  }, [currentListName])

  useEffect(() => {
    if (gameState === "playing") {
      timerRef.current = setInterval(() => {
        setTimeElapsed((prev) => prev + 1)
      }, 1000)
    } else {
      if (timerRef.current) clearInterval(timerRef.current)
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }, [gameState])

  const speakWord = useCallback((word: string) => {
    // Don't speak if the word contains Chinese characters or TTS is not supported
    const hasChinese = /[\u4e00-\u9fa5]/.test(word)
    if (hasChinese || !window.speechSynthesis) return

    // Cancel any ongoing speech to prevent overlap
    window.speechSynthesis.cancel()

    const utterance = new SpeechSynthesisUtterance(word)
    utterance.lang = "en-US" // Set language for better pronunciation
    window.speechSynthesis.speak(utterance)
  }, [])

  const showNotification = (message: string) => {
    setNotification(message)
    setTimeout(() => setNotification(""), 2000)
  }

  const generatePlaceholderBoard = (count: number) => {
    const placeholders = Array.from({ length: count * 2 }, (_, i) => ({
      id: `p-${i}`,
      text: "...",
      pairId: Math.floor(i / 2),
      status: "visible" as const,
      color: cardColors[i % cardColors.length],
    }))
    setGameBoard(placeholders)
  }

  const prepareNewRound = useCallback(
    (startIndex: number, count: number, shouldShuffle: boolean, wordList: WordPair[]) => {
      if (wordList.length === 0) return

      const listToUse = shouldShuffle ? shuffleArray(wordList) : wordList
      if (shouldShuffle) setCurrentWordIndex(0)

      const effectiveStartIndex = startIndex % listToUse.length
      const pairs = listToUse.slice(effectiveStartIndex, effectiveStartIndex + count)

      if (pairs.length < count && listToUse.length >= count) {
        const remaining = count - pairs.length
        pairs.push(...listToUse.slice(0, remaining))
        setCurrentWordIndex(remaining)
      } else {
        setCurrentWordIndex(effectiveStartIndex + pairs.length)
      }

      const board = pairs.flatMap(([word, answer], i) => [
        { id: `${i}-a`, text: word, pairId: i, status: "visible" as const, color: "" },
        { id: `${i}-b`, text: answer, pairId: i, status: "visible" as const, color: "" },
      ])

      const shuffledBoard = shuffleArray(board).map((card, i) => ({
        ...card,
        color: cardColors[i % cardColors.length],
      }))

      setGameBoard(shuffledBoard)
    },
    [],
  )

  const handleFileImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    const reader = new FileReader()
    const fileExtension = file.name.split(".").pop()?.toLowerCase()

    reader.onload = (e) => {
      const data = e.target?.result
      let validPairs: WordPair[] = []

      try {
        if (fileExtension === "json") {
          const json = JSON.parse(data as string)
          if (Array.isArray(json) && json.every((row) => Array.isArray(row) && row.length >= 2)) {
            validPairs = json.map((row) => [String(row[0]), String(row[1])])
          }
        } else if (fileExtension === "xlsx" || fileExtension === "xls") {
          const workbook = XLSX.read(data, { type: "array" })
          const sheetName = workbook.SheetNames[0]
          const worksheet = workbook.Sheets[sheetName]
          const json = XLSX.utils.sheet_to_json(worksheet, { header: 1 }) as string[][]
          validPairs = json
            .filter((row) => row && row.length >= 2 && row[0] && row[1])
            .map((row) => [String(row[0]), String(row[1])])
        }

        if (validPairs.length > 0) {
          const savedLists = localStorage.getItem("wordMatchUserLists")
          const userLists = savedLists ? JSON.parse(savedLists) : {}
          const newLists = { ...userLists, [file.name]: validPairs }
          localStorage.setItem("wordMatchUserLists", JSON.stringify(newLists))
          setAvailableLists({ ...builtInLists, ...newLists })
          setCurrentListName(file.name)
          showNotification(`Imported and saved ${file.name}!`)
        } else {
          showNotification(`Could not find valid word pairs in ${file.name}.`)
        }
      } catch (error) {
        console.error("File import error:", error)
        showNotification(`Error reading file ${file.name}. Please check the format.`)
      }
    }

    if (fileExtension === "json") {
      reader.readAsText(file)
    } else {
      reader.readAsArrayBuffer(file)
    }
  }

  const handleStartGame = () => {
    const wordList = availableLists[currentListName]
    if (!wordList || wordList.length === 0) {
      showNotification("Please select a valid word list!")
      return
    }

    setTimeElapsed(0)
    setGameState("playing")
    setIsFocusMode(true)
    prepareNewRound(0, pairCount, true, wordList)
  }

  const handlePauseGame = () => {
    setGameState("idle")
    setIsFocusMode(false)
  }

  const handleCardClick = (clickedCard: GameCard) => {
    if (isChecking || gameState !== "playing" || clickedCard.status !== "visible") return

    speakWord(clickedCard.text) // Add this line

    const newGameBoard = [...gameBoard]
    const cardIndex = newGameBoard.findIndex((c) => c.id === clickedCard.id)

    if (!firstSelection) {
      newGameBoard[cardIndex].status = "selected"
      setFirstSelection(newGameBoard[cardIndex])
      setGameBoard(newGameBoard)
    } else {
      if (firstSelection.id === clickedCard.id) return

      setIsChecking(true)
      const firstSelectionIndex = newGameBoard.findIndex((c) => c.id === firstSelection.id)

      if (firstSelection.pairId === clickedCard.pairId) {
        newGameBoard[cardIndex].status = "matched"
        newGameBoard[firstSelectionIndex].status = "matched"
        const successSound = new Audio("/audio/match-success.mp3")
        successSound.play().catch((e) => console.error("Error playing success sound:", e))
        setFirstSelection(null)
        setTimeout(() => {
          setGameBoard(newGameBoard)
          setIsChecking(false)
          if (newGameBoard.every((c) => c.status === "matched")) {
            setGameState("finished")
            setShowModal(true)
          }
        }, 300)
      } else {
        newGameBoard[cardIndex].status = "mismatched"
        newGameBoard[firstSelectionIndex].status = "mismatched"
        setGameBoard(newGameBoard)
        setTimeout(() => {
          newGameBoard[cardIndex].status = "visible"
          newGameBoard[firstSelectionIndex].status = "visible"
          setGameBoard([...newGameBoard])
          setFirstSelection(null)
          setIsChecking(false)
        }, 800)
      }
    }
  }

  const handleContinue = () => {
    setShowModal(false)
    setTimeElapsed(0)
    setGameState("playing")
    setIsFocusMode(true)
    prepareNewRound(currentWordIndex, pairCount, false, availableLists[currentListName])
  }

  const getCardClasses = (card: GameCard) => {
    let classes = `p-2 text-white rounded-lg flex items-center justify-center text-center font-semibold cursor-pointer transition-all duration-300 transform-gpu aspect-video ${card.color}`
    if (gameState !== "playing") classes += " cursor-not-allowed"

    switch (card.status) {
      case "selected":
        classes += " ring-4 ring-white scale-105"
        break
      case "mismatched":
        classes += " animate-shake bg-red-500"
        break
      case "matched":
        classes += " opacity-0 scale-0 pointer-events-none"
        break
      default:
        classes += " hover:scale-105"
    }
    return classes
  }

  return (
    <div
      className="min-h-screen bg-gray-50 text-gray-800 flex flex-col items-center p-4 sm:p-6 md:p-8 transition-all duration-300"
      data-focus-mode={isFocusMode}
    >
      {!isFocusMode && (
        <>
          <h1
            contentEditable
            onBlur={(e) => setTitle(e.currentTarget.textContent || "Word Match")}
            suppressContentEditableWarning
            className="text-4xl sm:text-5xl font-bold text-gray-700 mb-4 cursor-text outline-none focus:ring-2 focus:ring-blue-400 rounded-md px-2"
          >
            {title}
          </h1>
          <h2 className="text-lg font-medium text-gray-500 mb-4">{currentListName}</h2>

          <Card className="w-full max-w-5xl mb-6 shadow-md">
            <CardContent className="p-4 flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-4 w-full sm:w-auto">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline">
                      Select Word List
                      <ChevronDown className="ml-2 h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent>
                    <DropdownMenuLabel>Available Lists</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    {Object.keys(availableLists)
                      .sort()
                      .map((listName) => (
                        <DropdownMenuItem key={listName} onSelect={() => setCurrentListName(listName)}>
                          {listName}
                        </DropdownMenuItem>
                      ))}
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onSelect={() => fileInputRef.current?.click()}>
                      <Upload className="mr-2 h-4 w-4" />
                      Import New List...
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handleFileImport}
                  accept=".xlsx, .xls, .json"
                  className="hidden"
                />
                <Button onClick={handleStartGame}>
                  {gameState === "idle" ? <Play className="mr-2 h-4 w-4" /> : <RotateCcw className="mr-2 h-4 w-4" />}
                  {gameState === "idle" ? "Start Game" : "Restart"}
                </Button>
              </div>
              <div className="flex items-center gap-3 w-full sm:w-1/2">
                <span className="whitespace-nowrap text-sm font-medium">Pairs: {pairCount}</span>
                <Slider
                  value={[pairCount]}
                  onValueChange={(value) => setPairCount(value[0])}
                  min={5}
                  max={50}
                  step={1}
                  disabled={gameState === "playing"}
                />
              </div>
            </CardContent>
          </Card>
        </>
      )}

      <div
        className={`flex items-center gap-2 text-xl font-mono mb-6 bg-white px-4 py-2 rounded-lg shadow-sm transition-all duration-300 ${
          isFocusMode ? "mt-auto" : ""
        }`}
      >
        <Timer className="h-6 w-6 text-gray-500" />
        <span>Time: {timeElapsed}s</span>
      </div>

      <div
        className={`w-full max-w-7xl grid grid-cols-4 sm:grid-cols-5 md:grid-cols-8 lg:grid-cols-10 gap-2 sm:gap-3 transition-all duration-300 ${
          isFocusMode ? "mb-auto" : ""
        }`}
      >
        {gameBoard.map((card) => (
          <div key={card.id} className={getCardClasses(card)} onClick={() => handleCardClick(card)}>
            <span className="text-sm sm:text-base">{card.text}</span>
          </div>
        ))}
      </div>

      {isFocusMode && (
        <Button
          onClick={handlePauseGame}
          className="fixed bottom-5 right-5 rounded-full h-14 w-14 shadow-lg"
          aria-label="Pause Game"
        >
          <Pause className="h-6 w-6" />
        </Button>
      )}

      {notification && (
        <div className="fixed bottom-5 right-5 bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg animate-pulse z-50">
          {notification}
        </div>
      )}

      <Dialog open={showModal} onOpenChange={setShowModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="text-2xl text-center">Congratulations!</DialogTitle>
            <DialogDescription className="text-center">
              You matched all pairs in {timeElapsed} seconds.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button onClick={handleContinue} className="w-full">
              Continue Challenge
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
